### ISSUE TITLE
BREAKING CHANGE error

### ISSUE THREAD

**Issue by izzzzthewiz** [SnaBe/node-steam-market-fetcher#14]
Hi there, I recently installed this package and I am encountering the folloring error:
```
Module not found: Error: Can't resolve 'os' in 'C:\Users\User\Desktop\Websites\csskintrack\node_modules\@colors\colors\lib\system'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
	- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "os": false }
```

All I have done is initialized a new instance of the class like so:
```
import SteamMarketFetcher from 'steam-market-fetcher'
const Fetcher = new SteamMarketFetcher({
  currency: 'CAD',
  format: 'json'
})
```

I know the Readme mentions the documentation on the wiki of this repo should help when you encounter this, but I'm not sure what the solution is. Thank you in advance for any help!

**Comment by SnaBe** [comment]
Hi, can you tell me more about your dev environment? Like what framework you're using? TypeScript project or a similar Node.js configuration? I also assume you running the latest version 1.8.0

I'll look into it asap, but I'll need a little more info, as NPM's RunKit shows no errors after instantiation.

**Comment by izzzzthewiz** [comment]
I'm using react and I'm just trying to fetch from the API and display data.

**Comment by SnaBe** [comment]
Alright, I would refer you this previous error #6 that also discusses use of the module with React. The error is different but my conclusions is the same, however, feel free to create a feature request for browser support.
