### ISSUE TITLE
Currency error

### ISSUE THREAD

**Issue by matvejs16** [SnaBe/node-steam-market-fetcher#18]
Setting price to EUR but shows in USD, why that happens?

```javascript
const market = new SteamMarketFetcher({
     currency: 'EUR',
     format: 'json'
})
```

```typescript
const marketQuery = market.getMarketListings({
     query: 'AK-47',
     appid: 730
}) as Promise<GetMarketListingsResponse>

marketQuery.then(data => {
     console.log(data);
})
```

Response
```javascript
{
  success: true,
  start: 0,
  pagesize: 100,
  total_count: 388,
  searchdata: {
    query: 'AK-47',
    search_descriptions: false,
    total_count: 388,
    pagesize: 100,
    prefix: 'searchResults',
    class_prefix: 'market'
  },
  results: [
    {
      name: 'Sticker | Hello AK-47',
      hash_name: 'Sticker | Hello AK-47',
      sell_listings: 166,
      sell_price: 48,
      sell_price_text: '$0.48',
      app_icon: 'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/730/69f7ebe2735c366c65c0b33dae00e12dc40edbe4.jpg',
      app_name: 'Counter-Strike: Global Offensive',
      asset_description: [Object],
      sale_price_text: '$0.46'
    }
  ]
}

**Comment by SnaBe** [comment]
Hi,

The [getMarketListings](https://github.com/SnaBe/node-steam-market-fetcher/wiki#getmarketlistings--query-descriptions-appid-start-callback-) method calls the following endpoint - https://steamcommunity.com/market/search/render. This endpoint doesn't take the currency parameter as an input, resulting in the currency being rendered in dollars. 

Usually, Steam determines the currency based on your browser and displays prices in that currency. However, attaching your Steamcommunity cookie to the request would trick Steam into showing the prices in your local or default currency. This is something I could implement for the method, similar to [getMyHistory ](https://github.com/SnaBe/node-steam-market-fetcher/wiki#getmyhistory--cookie-callback-) and [getMyListings ](https://github.com/SnaBe/node-steam-market-fetcher/wiki#getmylistings--cookie-callback-).

Let me know if this has any interest. 

Best regards,
SnaBe
