### ISSUE TITLE
the '★' from knifes isn't supported

### ISSUE THREAD

**Issue by Faldin865** [SnaBe/node-steam-market-fetcher#4]
When passing a knife into the fetcher it return an error : "Request path contains unescaped characters".

I start the program with those arguments : 
Fetcher.getItemPrice('★ Paracord Knife | Fade (Factory New)', 730).then((price) => console.log(price)).catch((err) => console.log(err.message));

**Comment by SnaBe** [comment]
Thanks for the report, this should be patched in the upcoming 1.5 release.

The release also includes.
* A method for getting an item's price history.
* More query options for most if not all market endpoints.

I'll close this issue once the new version is available.
